Repository danielsogl/awesome-cordova-plugins, pull requests merged in 2018-12, with the labels that each got.

#2820 feat(downloader): add plugin
  src/@ionic-native/plugins/downloader/index.ts
Labels: target: minor

#2827 docs(camera): improve docs
  src/@ionic-native/plugins/camera/index.ts
Labels: target: patch

#2828 docs(network): fix typo
  src/@ionic-native/plugins/network/index.ts
Labels: target: patch

#2825 fix(local-notifications): update type of the every property
  src/@ionic-native/plugins/local-notifications/index.ts
Labels: target: patch

#2839 chore(template): reorder imports
  scripts/templates/wrap-min.tmpl
  scripts/templates/wrap.tmpl
Labels: not-an-issue
