Repository danielsogl/awesome-cordova-plugins, pull requests merged in 2018-10, with the labels that each got.

#2763 feat(firebase-messaging): add revokeToken function
  src/@ionic-native/plugins/firebase-messaging/index.ts
Labels: target: patch

#2761 feat(speechkit): plugin updated with voice parameter
  src/@ionic-native/plugins/speechkit/index.ts
Labels: target: patch

#2755 docs(apple-wallet): update example
  src/@ionic-native/plugins/apple-wallet/index.ts
Labels: target: patch

#2754 refactor(network): add enum for connection types
  src/@ionic-native/plugins/network/index.ts
Labels: target: patch

#2751 fix(keyboard) isVisible property missing
  src/@ionic-native/plugins/keyboard/index.ts
Labels: target: patch

#2753 feat(admob-plus): Add admob-plus
  src/@ionic-native/plugins/admob-plus/index.ts
Labels: target: minor

#2759 feat(lastCam): add plugin
  src/@ionic-native/plugins/last-cam/index.ts
Labels: new-plugin, target: minor

#2777 feat(nfc): add NFC readerMode
  src/@ionic-native/plugins/nfc/index.ts
Labels: target: patch

#2779 fix(local-notifications): add missing functions
  src/@ionic-native/plugins/local-notifications/index.ts
Labels: target: patch

#2780 docs(one-signal): fix target url for notification icon
  src/@ionic-native/plugins/onesignal/index.ts
Labels: target: patch

#2792 feat(crashlytics): allow user to set userIdentifier for crashlytics
  src/@ionic-native/plugins/firebase/index.ts
Labels: target: patch

#2795 docs(mobile-accessibility): update usage
  src/@ionic-native/plugins/mobile-accessibility/index.ts
Labels: target: patch

#2794 docs(social-sharing): update web share api link
  src/@ionic-native/plugins/social-sharing/index.ts
Labels: target: patch
