Repository danielsogl/awesome-cordova-plugins, pull requests merged in 2018-07, with the labels that each got.

#2576 feat(streaming-media): add new parameters & docs
  src/@ionic-native/plugins/streaming-media/index.ts
Labels: target: patch

#2544 fix(health-kit): add missing checkAuthStatus param
  src/@ionic-native/plugins/health-kit/index.ts
Labels: needs reply, target: patch

#2582 fix(app-version): fix getVersionCode to return number
  src/@ionic-native/plugins/app-version/index.ts
Labels: target: patch

#2586 docs(sqlite): Add interface for transaction callback function argument
  src/@ionic-native/plugins/sqlite/index.ts
Labels: target: patch

#2587 feat(network-interface): match latest plugin release
  src/@ionic-native/plugins/network-interface/index.ts
Labels: target: patch

#2588 docs(linkedin): fix example
  src/@ionic-native/plugins/linkedin/index.ts
Labels: target: patch

#2594 fix(ble): change signature for autoConnect
  src/@ionic-native/plugins/ble/index.ts
Labels: target: patch

#2593 docs(document-picker): fix example
  src/@ionic-native/plugins/document-picker/index.ts
Labels: target: patch

#2592 fix(sqlite): mark optional arguments for executeSql
  src/@ionic-native/plugins/sqlite/index.ts
Labels: target: patch

#2580 feat(abbyy-rtr): add ABBYY Real-Time Recognition plugin
  src/@ionic-native/plugins/abbyy-rtr/index.ts
Labels: new-plugin, target: minor

#2590 feat(classkit): add ClassKit plugin
  src/@ionic-native/plugins/class-kit/index.ts
Labels: new-plugin, target: minor

#2591 feat(alipay): replace plugin
  src/@ionic-native/plugins/alipay/index.ts
Labels: target: minor

#2601 feat(ccm): replace plugin source
  src/@ionic-native/plugins/fcm/index.ts
Labels: target: minor

#2602 docs(network-interface): update example
  src/@ionic-native/plugins/network-interface/index.ts
Labels: target: patch

#2605 fix(nfs): Optional arguments for records like textRecord
  src/@ionic-native/plugins/nfc/index.ts
Labels: target: patch

#2607 fix(user-agent): Plugin not installed
  src/@ionic-native/plugins/user-agent/index.ts
Labels: target: patch

#2611 refactor: Improve Ionic Native warnings
  src/@ionic-native/core/util.ts
Labels: target: patch

#2604 feat(webengage): add webengage plugin
  src/@ionic-native/plugins/webengage/index.ts
Labels: new-plugin, target: minor
