Repository danielsogl/awesome-cordova-plugins, pull requests merged in 2019-06, with the labels that each got.

#3025 feat(biometric-wrapper): add plugin
  src/@ionic-native/plugins/biometric-wrapper/index.ts
Labels: target: minor

#3026 feat(full-screen-image): add plugin
  src/@ionic-native/plugins/full-screen-image/index.ts
Labels: target: minor

#3037 feat(in-app-purchase-2): update TypeScript definitions
  src/@ionic-native/plugins/in-app-purchase-2/index.ts
Labels: target: patch

#3041 feat(blinkid): added support for card overlay
  src/@ionic-native/plugins/blinkid/index.ts
Labels: target: patch

#3043 feat(document-scanner): add plugin
  src/@ionic-native/plugins/document-scanner/index.ts
Labels: target: minor

#3044 feat(ocr): add plugin
  src/@ionic-native/plugins/ocr/index.ts
Labels: target: minor

#3047 fix(firebase-messaging): add missing `getToken` options
  src/@ionic-native/plugins/firebase-messaging/index.ts
Labels: target: patch

#3048 feat(device-accounts): Adding getPermissionsByType function
  src/@ionic-native/plugins/device-accounts/index.ts
Labels: target: patch

#3049 feat(one signal): add missing "setExternalUserId" and "removeExternalUserId" functions
  src/@ionic-native/plugins/onesignal/index.ts
Labels: target: patch

#3051 feat(diagnostic): add requestRemoteNotificationsAuthorization method
  src/@ionic-native/plugins/diagnostic/index.ts
Labels: target: patch

#3053 feat(apple-wallet): support plugin version 3.0
  src/@ionic-native/plugins/apple-wallet/index.ts
Labels: target: minor

#3054 fix(music-control): use correct input type
  src/@ionic-native/plugins/music-controls/index.ts
Labels: target: patch

#3055 feat(in-app-purchase-2): add documentation
  src/@ionic-native/plugins/in-app-purchase-2/index.ts
Labels: target: patch

#3062 docs(launch-review): add missing bracket
  src/@ionic-native/plugins/launch-review/index.ts
Labels: improve docs, target: patch

#3063 fix(in-app-purchase-2): add missing option to register function
  src/@ionic-native/plugins/in-app-purchase-2/index.ts
Labels: target: patch

#3059 fix(firebase): add missing decorator to clearAllNotifications
  src/@ionic-native/plugins/firebase/index.ts
Labels: target: patch
