Repository danielsogl/awesome-cordova-plugins, pull requests merged in 2019-08, with the labels that each got.

#3117 feat(smartlook): add plugin
  src/@ionic-native/plugins/smartlook/index.ts
Labels: target: minor

#3119 fix(intercom): added logout, displayHelpCenter, sendPushTokenToIntercom
  src/@ionic-native/plugins/intercom/index.ts
Labels: target: patch

#3120 feat(http): add sendRequest responseType option
  src/@ionic-native/plugins/http/index.ts
Labels: target: patch

#3127 docs(image-picker): set docs repo url to active repo
  src/@ionic-native/plugins/image-picker/index.ts
Labels: target: patch

#3128 fix(ms-adal): use correct accessTokenType prop
  src/@ionic-native/plugins/ms-adal/index.ts
Labels: target: patch

#3130 doc(unvired-cordova-sdk): update doc
  src/@ionic-native/plugins/unvired-cordova-sdk/index.ts
Labels: target: patch

#3131 fix(background-geolocation): enum not string
  src/@ionic-native/plugins/background-geolocation/index.ts
Labels: target: patch

#3134 fix(chooser): @param accept is supposed to be optional
  src/@ionic-native/plugins/chooser/index.ts
Labels: target: patch

#3136 feat(file-chooser): add missing options param
  src/@ionic-native/plugins/file-chooser/index.ts
Labels: target: patch

#3137 docs(wonderpush): fix usage formatting
  src/@ionic-native/plugins/wonderpush/index.ts
Labels: improve docs

#3138 feat(google-play-games-services): add new synchronous methods
  src/@ionic-native/plugins/google-play-games-services/index.ts
Labels: target: patch

#3142 fix(in-app-browser): update types to match cordova-plugin-inappbrowser 3.1.0
  src/@ionic-native/plugins/in-app-browser/index.ts
Labels: target: patch

#3143 fix(theme-detection): added android platform
  src/@ionic-native/plugins/theme-detection/index.ts
Labels: target: patch

#3144 fix(anyline): added official plugin
  src/@ionic-native/plugins/anyline/index.ts
Labels: target: patch

#3146 fix(network): rename onchange method name
  src/@ionic-native/plugins/network/index.ts
Labels: target: minor

#3149 Add response type to AndroidPermission plugin permission checking
  src/@ionic-native/plugins/android-permissions/index.ts
Labels: target: patch

#3147 doc(unvired-cordova-sdk): update doc
  src/@ionic-native/plugins/unvired-cordova-sdk/index.ts
Labels: target: patch
