Repository danielsogl/awesome-cordova-plugins, pull requests merged in 2019-07, with the labels that each got.

#3061 feat(unvired-cordova-sdk): add plugin
  src/@ionic-native/plugins/unvired-cordova-sdk/index.ts
Labels: target: minor

#3071 feat(diagnostic): add DENIED_ONCE introduced by diagnostic v5
  src/@ionic-native/plugins/diagnostic/index.ts
Labels: target: patch

#3080 feat(sum-up): add plugin
  src/@ionic-native/plugins/sum-up/index.ts
Labels: target: minor

#3081 fix(alipay): use correct pluginRef
  src/@ionic-native/plugins/alipay/index.ts
Labels: target: patch

#3075 feat(calendar): add deleteEventById function
  src/@ionic-native/plugins/calendar/index.ts
Labels: target: patch

#3068 refactor(core): allow rxjs 5.5 as peer dependency
  scripts/tasks/publish.ts
Labels: discuss

#3082 feat(theme-detection): add plugin
  src/@ionic-native/plugins/theme-detection/index.ts
Labels: target: minor

#3086 fix(biocatch): added android platform and updated repo
  src/@ionic-native/plugins/biocatch/index.ts
Labels: target: patch

#3090 doc(unvired-cordova-sdk): doc update
  src/@ionic-native/plugins/unvired-cordova-sdk/index.ts
Labels: target: patch

#3094 docs(deeplinks): Added informations about AASA (iOS) and Asset Links (Android) to documentation
  src/@ionic-native/plugins/deeplinks/index.ts
Labels: target: patch

#3096 fix(barcode-scanner): add missing shouldAutorotate property
  src/@ionic-native/plugins/barcode-scanner/index.ts
Labels: target: patch

#3101 feat(anyline): add plugin
  src/@ionic-native/plugins/anyline/index.ts
Labels: target: minor

#3106 feat(cordova-plugin-firebasex): Add plugin
  src/@ionic-native/plugins/firebase-x/index.ts
Labels: target: minor

#3107 feat(wonderpush): add plugin
  src/@ionic-native/plugins/wonderpush/index.ts
Labels: target: minor

#3108 doc(unvired-cordova-sdk): improve doc
  src/@ionic-native/plugins/unvired-cordova-sdk/index.ts
Labels: target: patch

#3114 feat(urbanairship): add plugin
  src/@ionic-native/plugins/urbanairship/index.ts
Labels: target: minor
