Repository danielsogl/awesome-cordova-plugins, pull requests merged in 2019-01, with the labels that each got.

#2831 fix(health): fix typos
  src/@ionic-native/plugins/health/index.ts
  src/@ionic-native/plugins/nfc/index.ts
Labels: target: patch

#2832 docs(camera): update xml in warning part
  src/@ionic-native/plugins/camera/index.ts
Labels: target: patch

#2833 feat(blinkid): add plugin
  src/@ionic-native/plugins/blinkid/index.ts
Labels: target: minor

#2835 docs(firebase): add onNotificationOpen usage example
  src/@ionic-native/plugins/firebase/index.ts
Labels: target: patch

#2838 feat(baidu-push): add plugin
  src/@ionic-native/plugins/baidu-push/index.ts
Labels: target: minor

#2857 feat(gao-de-location): add plugin
  src/@ionic-native/plugins/gao-de-location/index.ts
Labels: target: patch

#2862 feat(analytics-firebase): add plugin
  src/@ionic-native/plugins/analytics-firebase/index.ts
Labels: target: minor

#2863 feat(in-app-browser): add 'beforeload' as option
  src/@ionic-native/plugins/in-app-browser/index.ts
Labels: target: patch

#2864 feat(admob): add plugin
  src/@ionic-native/plugins/admob/index.ts
Labels: target: minor

#2872 feat(adjust): add adjust sdk plugin
  src/@ionic-native/plugins/adjust/index.ts
Labels: target: minor

#2881 fix(bluetooth-le): Fix typo in interface definition
  src/@ionic-native/plugins/bluetooth-le/index.ts
Labels: target: patch

#2393 feat(background-geolocation): add v3 functions and interfaces
  src/@ionic-native/plugins/background-geolocation/index.ts
Labels: WIP, target: patch

#2891 fix(bluetooth-le): Fix typo in InitializeResult interface definition
  src/@ionic-native/plugins/bluetooth-le/index.ts
Labels: target: patch
