Repository danielsogl/awesome-cordova-plugins, pull requests merged in 2019-02, with the labels that each got.

#2914 fix(build): fixed duplicate import identifiers
  scripts/build/transformers/imports.ts
Labels: target: patch

#2924 docs(background-geolocation): update usage doc
  src/@ionic-native/plugins/background-geolocation/index.ts
Labels: target: patch

#2920 fix(google-play-games-services): correct Cordova plugin name typo
  src/@ionic-native/plugins/google-play-games-services/index.ts
Labels: target: patch

#2915 cordova-plugin-abbyy-rtr-sdk version 1.0.9 new option update
  src/@ionic-native/plugins/abbyy-rtr/index.ts
Labels: target: patch

#2913 fix: Add 'legacy' as valid option to setSSLCertMode
  src/@ionic-native/plugins/http/index.ts
Labels: target: patch

#2910 feat(http): sendRequest
  src/@ionic-native/plugins/http/index.ts
Labels: target: patch

#2895 feat(photo-viewer): add new params
  src/@ionic-native/plugins/photo-viewer/index.ts
Labels: target: patch

#2923 feat(quikkly): add plugin
  src/@ionic-native/plugins/quikkly/index.ts
Labels: target: minor

#2917 feat(magnetometer): add new plugin
  src/@ionic-native/plugins/magnetometer/index.ts
Labels: target: minor

#2916 feat(cordova.plugin.zoom):add new plugin
  src/@ionic-native/plugins/zoom/index.ts
Labels: target: minor

#2883 feat(luxand plugin): add luxand Face SDK plugin
  src/@ionic-native/plugins/luxand/index.ts
Labels: needs reply, target: minor

#2931 feat(clevertap): update for latest CleverTap Cordova plugin
  src/@ionic-native/plugins/clevertap/index.ts
Labels: needs reply, target: minor

#2935 feat(apple-wallet): update wrapper to release 2.0
  src/@ionic-native/plugins/apple-wallet/index.ts
Labels: target: patch
