Repository danielsogl/awesome-cordova-plugins, pull requests merged in 2020-06, with the labels that each got.

#3421 feat(ios-aswebauthenticationsession): add plugin
  src/@ionic-native/plugins/ios-aswebauthenticationsession-api/index.ts
Labels: needs reply, target: minor

#3455 fix(launch-review): Allow rating() callback to be invoked multiple times
  src/@ionic-native/plugins/launch-review/index.ts
Labels: target: patch

#3456 fix(app-rate): Add missing "openUrl" property to AppRatePreferences object
  src/@ionic-native/plugins/app-rate/index.ts
Labels: target: patch

#3457 fix(firebase-x): indicate callback methods to verifyPhoneNumber
  src/@ionic-native/plugins/firebase-x/index.ts
Labels: target: patch

#3458 feat(firebase-x): add missing methods, incl. authenticateUserWithApple
  src/@ionic-native/plugins/firebase-x/index.ts
Labels: target: patch

#3461 feat(admob): add interfaces and method typings
  src/@ionic-native/plugins/admob/index.ts
Labels: target: minor

#3463 feat(camera-preview): add record video functions
  src/@ionic-native/plugins/camera-preview/index.ts
Labels: target: patch

#3465 feat(build-info): add plugin
  src/@ionic-native/plugins/build-info/index.ts
Labels: target: minor

#3466 feat(vibes): add support for inbox messaging
  src/@ionic-native/plugins/vibes/index.ts
Labels: target: patch

#3467 fix(camera-preview): tapFocus
  src/@ionic-native/plugins/camera-preview/index.ts
Labels: target: patch
